---
# App secrets (JWT, etc.)
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwt-secret: {{ .Values.secret.appSecrets.jwtSecret }}

---
# MongoDB credentials (copy from database namespace)
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  root-username: {{ .Values.secret.mongoSecrets.rootUsername }}
  root-password: {{ .Values.secret.mongoSecrets.rootPassword }}
  mongo-auth-db: {{ .Values.secret.mongoSecrets.authDatabase }}